### PR TITLE
Add Dart

### PR DESCRIPTION
**Pull request by seanohue**
Let it no longer be said that no one uses Dart.

### CODE REVIEW

**Comment by Keith-S-Thompson** [comment]
Thank you for the pull request, but I'm not going to merge it. As I should have made clear in the README (and I'll update it now), this is not intended to be a collaborative project. It's my own little playground.

I'll gladly accept bug reports, but not new implementations.

You might be interested in [Rosetta Code](http://rosettacode.org/wiki/Rosetta_Code) (which apparently already has a Dart implementation of FizzBuzz).

But thank you for reminding me about Dart. I'll probably add a Dart implementation Real Soon Now.

Thanks again.

**Comment by seanohue** [comment]
No problem! Thanks for the update, and for pointing me to Rosetta Code.


Sean O'Donohue
--
*Web Application Developer*
*GM NGI Onsite Team*


*"I urge you to please notice when you are happy, and exclaim or murmur or
think at some point, “If this isn’t nice, I don’t know what is.”*
*- Kurt Vonnegut*

**Comment by seanohue** [comment]
Feel free to steal and try to one-up my solution ;) I'll be looking forward to seeing it.

**Comment by Keith-S-Thompson** [comment]
Actually I added `fizzbuzz.dart` this morning (without reading your version, just because...).

It rather vanilla and doesn't really show off the language, but it works.

**Comment by seanohue** [comment]
Cool, good to know. I'll check out your version too.

**Pull request closed without merging**
